// <auto-generated />
using System;
using Bank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("w13_Quiz.Entities.Card", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FailedPasswordAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.HasKey("CardNumber");

                    b.ToTable("Cards", t =>
                        {
                            t.HasCheckConstraint("CK_Card_Balance_NonNegative", "[Balance] >= 0");

                            t.HasCheckConstraint("CK_Card_CardNumber_Valid", "LEN([CardNumber]) = 16 AND [CardNumber] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Card_FailedPasswordAttempts", "[FailedPasswordAttempts] >= 0 AND [FailedPasswordAttempts] <= 3");

                            t.HasCheckConstraint("CK_Card_Password_Valid", "LEN([Password]) = 4 AND [Password] NOT LIKE '%[^0-9]%'");
                        });

                    b.HasData(
                        new
                        {
                            CardNumber = "1000000000000001",
                            Balance = 25000m,
                            FailedPasswordAttempts = 0,
                            HolderName = "Amir Fayazi",
                            IsActive = true,
                            Password = "1111"
                        },
                        new
                        {
                            CardNumber = "1000000000000002",
                            Balance = 40000m,
                            FailedPasswordAttempts = 0,
                            HolderName = "Sara Ahmadi",
                            IsActive = true,
                            Password = "2222"
                        },
                        new
                        {
                            CardNumber = "1000000000000003",
                            Balance = 18000m,
                            FailedPasswordAttempts = 1,
                            HolderName = "Reza Mohammadi",
                            IsActive = true,
                            Password = "3333"
                        },
                        new
                        {
                            CardNumber = "1000000000000004",
                            Balance = 65000m,
                            FailedPasswordAttempts = 0,
                            HolderName = "Neda Karimi",
                            IsActive = true,
                            Password = "4444"
                        },
                        new
                        {
                            CardNumber = "1000000000000005",
                            Balance = 12000m,
                            FailedPasswordAttempts = 2,
                            HolderName = "Ali Hosseini",
                            IsActive = true,
                            Password = "5555"
                        },
                        new
                        {
                            CardNumber = "1000000000000006",
                            Balance = 90000m,
                            FailedPasswordAttempts = 0,
                            HolderName = "Mina Moradi",
                            IsActive = true,
                            Password = "6666"
                        },
                        new
                        {
                            CardNumber = "1000000000000007",
                            Balance = 35000m,
                            FailedPasswordAttempts = 0,
                            HolderName = "Arman Rahimi",
                            IsActive = true,
                            Password = "7777"
                        },
                        new
                        {
                            CardNumber = "1000000000000008",
                            Balance = 50000m,
                            FailedPasswordAttempts = 0,
                            HolderName = "Leila Akbari",
                            IsActive = true,
                            Password = "8888"
                        },
                        new
                        {
                            CardNumber = "1000000000000009",
                            Balance = 30000m,
                            FailedPasswordAttempts = 3,
                            HolderName = "Blocked Source",
                            IsActive = false,
                            Password = "9999"
                        },
                        new
                        {
                            CardNumber = "1000000000000010",
                            Balance = 45000m,
                            FailedPasswordAttempts = 3,
                            HolderName = "Blocked Destination",
                            IsActive = false,
                            Password = "1010"
                        });
                });

            modelBuilder.Entity("w13_Quiz.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DestinationCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("SourceCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("DestinationCardNumber");

                    b.HasIndex("SourceCardNumber");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Transaction_DifferentCards", "[SourceCardNumber] <> [DestinationCardNumber]");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 175m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 1, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 250m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 1, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 325m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 2, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 400m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 2, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 5,
                            Amount = 475m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 2, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 6,
                            Amount = 550m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 7,
                            Amount = 625m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 3, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 8,
                            Amount = 700m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 9,
                            Amount = 775m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 3, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 10,
                            Amount = 850m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 3, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 11,
                            Amount = 925m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 4, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 12,
                            Amount = 1000m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 4, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 13,
                            Amount = 1075m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 4, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 14,
                            Amount = 1150m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 4, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 15,
                            Amount = 1225m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 5, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 16,
                            Amount = 1300m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 5, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 17,
                            Amount = 1375m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 5, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 18,
                            Amount = 1450m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 5, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 19,
                            Amount = 1525m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 6, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 20,
                            Amount = 100m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 6, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 21,
                            Amount = 175m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 6, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 22,
                            Amount = 250m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 6, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 23,
                            Amount = 325m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 7, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 24,
                            Amount = 400m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 7, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 25,
                            Amount = 475m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 7, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 26,
                            Amount = 550m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 7, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 27,
                            Amount = 625m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 8, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 28,
                            Amount = 700m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 8, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 29,
                            Amount = 775m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 30,
                            Amount = 850m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 8, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 31,
                            Amount = 925m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 9, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 32,
                            Amount = 1000m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 9, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 33,
                            Amount = 1075m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 9, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 34,
                            Amount = 1150m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 9, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 35,
                            Amount = 1225m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 10, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 36,
                            Amount = 1300m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 37,
                            Amount = 1375m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 10, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 38,
                            Amount = 1450m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 10, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 39,
                            Amount = 1525m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 11, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 40,
                            Amount = 100m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 11, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 41,
                            Amount = 175m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 11, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 42,
                            Amount = 250m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 11, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 43,
                            Amount = 325m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 12, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 44,
                            Amount = 400m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 12, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 45,
                            Amount = 475m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 12, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 46,
                            Amount = 550m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 12, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 47,
                            Amount = 625m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 13, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 48,
                            Amount = 700m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 13, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 49,
                            Amount = 775m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 13, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 50,
                            Amount = 850m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 13, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 51,
                            Amount = 925m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 14, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 52,
                            Amount = 1000m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 14, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 53,
                            Amount = 1075m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 14, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 54,
                            Amount = 1150m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 14, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 55,
                            Amount = 1225m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 15, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 56,
                            Amount = 1300m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 15, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 57,
                            Amount = 1375m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 15, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 58,
                            Amount = 1450m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 15, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 59,
                            Amount = 1525m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 16, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 60,
                            Amount = 100m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 16, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 61,
                            Amount = 175m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 16, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 62,
                            Amount = 250m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 16, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 63,
                            Amount = 325m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 17, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 64,
                            Amount = 400m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 17, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 65,
                            Amount = 475m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 17, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 66,
                            Amount = 550m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 17, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 67,
                            Amount = 625m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 18, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 68,
                            Amount = 700m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 18, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 69,
                            Amount = 775m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 18, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 70,
                            Amount = 850m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 18, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 71,
                            Amount = 925m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 19, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 72,
                            Amount = 1000m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 19, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 73,
                            Amount = 1075m,
                            DestinationCardNumber = "1000000000000005",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000001",
                            TransactionDate = new DateTime(2026, 9, 19, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 74,
                            Amount = 1150m,
                            DestinationCardNumber = "1000000000000007",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000002",
                            TransactionDate = new DateTime(2026, 9, 19, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 75,
                            Amount = 1225m,
                            DestinationCardNumber = "1000000000000001",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000003",
                            TransactionDate = new DateTime(2026, 9, 20, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 76,
                            Amount = 1300m,
                            DestinationCardNumber = "1000000000000003",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000004",
                            TransactionDate = new DateTime(2026, 9, 20, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 77,
                            Amount = 1375m,
                            DestinationCardNumber = "1000000000000006",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000005",
                            TransactionDate = new DateTime(2026, 9, 20, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 78,
                            Amount = 1450m,
                            DestinationCardNumber = "1000000000000008",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000006",
                            TransactionDate = new DateTime(2026, 9, 20, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 79,
                            Amount = 1525m,
                            DestinationCardNumber = "1000000000000002",
                            IsSuccessful = true,
                            SourceCardNumber = "1000000000000007",
                            TransactionDate = new DateTime(2026, 9, 21, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 80,
                            Amount = 100m,
                            DestinationCardNumber = "1000000000000004",
                            IsSuccessful = false,
                            SourceCardNumber = "1000000000000008",
                            TransactionDate = new DateTime(2026, 9, 21, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("w13_Quiz.Entities.Transaction", b =>
                {
                    b.HasOne("w13_Quiz.Entities.Card", "DestinationCard")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("DestinationCardNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w13_Quiz.Entities.Card", "SourceCard")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SourceCardNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationCard");

                    b.Navigation("SourceCard");
                });

            modelBuilder.Entity("w13_Quiz.Entities.Card", b =>
                {
                    b.Navigation("ReceivedTransactions");

                    b.Navigation("SentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
